# Generated by Django 6.0.4 on 2026-04-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='exported_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='integrity_hash',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
