# Generated by Django 6.0.4 on 2026-04-17 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_auditevent_archived_at_auditevent_exported_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditIntegrityCheckpoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("sequence", models.PositiveIntegerField(db_index=True, unique=True)),
                ("anchor_hash", models.CharField(db_index=True, max_length=64)),
                ("signature", models.CharField(max_length=128)),
                ("signer", models.CharField(default="hmac-sha256", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anchor_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrity_checkpoints",
                        to="common.auditevent",
                    ),
                ),
            ],
            options={"ordering": ("-sequence",)},
        ),
        migrations.CreateModel(
            name="AuditIntegrityVerification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("passed", "Passed"), ("failed", "Failed")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("checked_events", models.PositiveIntegerField(default=0)),
                ("last_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checkpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to="common.auditintegritycheckpoint",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
