# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_alter_tenant_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributedlock",
            name="fencing_counter",
            field=models.BigIntegerField(default=0),
        ),
    ]
