# Generated by Django 6.0.4 on 2026-04-20 00:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0009_alter_tenant_deleted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("key", models.SlugField(db_index=True, max_length=96, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("default_channels", models.JSONField(blank=True, default=list)),
                ("allow_user_opt_out", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "indexes": [models.Index(fields=["is_active", "key"], name="notif_type_active_key_idx")],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("unread", "Unread"), ("read", "Read"), ("archived", "Archived")],
                        db_index=True,
                        default="unread",
                        max_length=16,
                    ),
                ),
                ("dedup_key", models.CharField(blank=True, default="", max_length=255)),
                ("published_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notification.notificationtype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["recipient", "status", "-published_at"], name="notif_rcpt_status_pub_idx"),
                    models.Index(fields=["tenant", "recipient", "-published_at"], name="notif_tenant_rcpt_pub_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedup_key", ""), _negated=True),
                        fields=("recipient", "notification_type", "dedup_key"),
                        name="notif_rcpt_type_dedup_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDigest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("window_start", models.DateTimeField(db_index=True)),
                ("window_end", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["recipient", "status", "-window_end"], name="notif_digest_user_status_idx"),
                    models.Index(fields=["tenant", "status", "-window_end"], name="notif_digest_tenant_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "window_start", "window_end"),
                        name="notif_digest_user_window_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("realtime", "Realtime"),
                            ("digest", "Digest"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=True)),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="notification.notificationtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "channel"], name="notif_pref_user_channel_idx"),
                    models.Index(fields=["notification_type", "channel"], name="notif_pref_type_channel_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "notification_type", "channel"),
                        name="notif_pref_user_type_channel_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("realtime", "Realtime"),
                            ("digest", "Digest"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("next_attempt_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notification.notification",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status", "next_attempt_at"], name="notif_deliv_status_retry_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "channel"),
                        name="notif_delivery_notification_channel_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="notificationdigest",
            name="notifications",
            field=models.ManyToManyField(blank=True, related_name="digests", to="notification.notification"),
        ),
    ]
